### ISSUE TITLE
PPrint throws errors on unicode characters and fails.

### ISSUE THREAD

**Issue by ThatOneRoadie** [fake-name/PatreonArchiver#1]
Error is:

	`Main.MainThread - CRITICAL - Uncaught exception!
	Main.MainThread - CRITICAL - Uncaught exception
	Traceback (most recent call last):
	  File "run.py", line 12, in <module>
		go()
	  File "run.py", line 8, in go
		scraper.run()
	  File "C:\Users\ThatOneRoadie\Downloads\PatreonArchiver-master\PatreonArchiver-master\Scrape.py", line 286, in run
		self.fetch_all()
	  File "C:\Users\ThatOneRoadie\Downloads\PatreonArchiver-master\PatreonArchiver-master\Scrape.py", line 279, in fetch_all
		self.fetch_post(postid, c_creator)
	  File "C:\Users\ThatOneRoadie\Downloads\PatreonArchiver-master\PatreonArchiver-master\Scrape.py", line 246, in fetch_post
		self.save_json(aname, pid, post)
	  File "C:\Users\ThatOneRoadie\Downloads\PatreonArchiver-master\PatreonArchiver-master\Scrape.py", line 179, in save_json
		fp.write(pprint.pformat(filecontent))
	  File "C:\Users\ThatOneRoadie\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
		return codecs.charmap_encode(input,self.errors,encoding_table)[0]
	UnicodeEncodeError: 'charmap' codec can't encode characters in position 9121-9126: character maps to <undefined>`

**Comment by fake-name** [comment]
I think this is probably an issue with your shell encoding, but I can patch around it to force UTF-8 without too much issue. Hangon.
